# Generated by Django 5.2.6 on 2026-03-12 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('group_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earing', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep', to='accounts.farm')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sheepfold.sheep')),
            ],
            options={
                'unique_together': {('farm', 'earing')},
            },
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('milk', models.DecimalField(decimal_places=2, help_text='liter', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='sheepfold.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='BirthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('lambs', models.ManyToManyField(blank=True, related_name='birth_event', to='sheepfold.sheep')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_events', to='sheepfold.sheep')),
            ],
        ),
    ]
