# Generated by Django 5.2.6 on 2025-12-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheep',
            name='age',
        ),
        migrations.RemoveField(
            model_name='sheep',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sheep',
            name='name',
        ),
        migrations.AddField(
            model_name='sheep',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sheep',
            name='earing',
            field=models.CharField(default='no_earing', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheep',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='sheep',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sheepfold.sheep'),
        ),
        migrations.CreateModel(
            name='BirthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('lambs', models.ManyToManyField(blank=True, related_name='birth_event', to='sheepfold.sheep')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_events', to='sheepfold.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('milk', models.DecimalField(decimal_places=2, help_text='liter', max_digits=5)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='sheepfold.sheep')),
            ],
        ),
    ]
