# Generated by Django 5.2.6 on 2026-03-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
        ('sheepfold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_batch', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('record_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='accounts.farm')),
                ('sheep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='sheepfold.sheep')),
            ],
        ),
    ]
