# Generated by Django 5.2.6 on 2026-01-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0002_remove_sheep_age_remove_sheep_id_remove_sheep_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('group_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
