# Generated by Django 5.2.6 on 2026-04-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_calendar_token'),
        ('sheepfold', '0002_healthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='group',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('med', 'Med'), ('low', 'Low'), ('dry', 'Dry'), ('ram', 'Ram'), ('ready', 'Ready for Birth')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sheep',
            name='ready_for_birth',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FarmMilkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_days', models.PositiveIntegerField(default=30)),
                ('high_threshold', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('med_threshold', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('low_threshold', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milk_settings', to='accounts.farm')),
            ],
        ),
    ]
