# Generated by Django 5.2.6 on 2026-04-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0003_add_sheep_groups_and_farmmilksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired', to='sheepfold.sheep'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
    ]
