# Generated by Django 5.2.6 on 2026-04-23 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_calendar_token'),
        ('sheepfold', '0004_sheep_father_alter_sheep_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_date', models.DateField()),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('sample_ref', models.CharField(blank=True, max_length=100)),
                ('protein_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('fat_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('snf_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('lactose_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('casein_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('water_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('freezing_point', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('foreign_milk_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('antibiotics_detected', models.BooleanField(blank=True, null=True)),
                ('aflatoxin_m1', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('total_bacteria_count', models.BigIntegerField(blank=True, null=True)),
                ('scc', models.BigIntegerField(blank=True, null=True)),
                ('clostridia', models.BigIntegerField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='milk_analyses/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_analyses_uploaded', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_analyses', to='accounts.farm')),
            ],
            options={
                'ordering': ['-sampling_date', '-id'],
                'indexes': [models.Index(fields=['farm', '-sampling_date'], name='sheepfold_m_farm_id_b044b4_idx')],
            },
        ),
    ]
